config/routes.rb
Bandera::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #devise_scope :user do
  #  get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #  get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #end

  root :to => "home#index"
  resources :videos
  get 'pages/about' => "pages#about"
  get 'location/get' => "locations#show"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :videos, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first

    logger.info "user info: #{auth.inspect}"

    city, country = auth[:info][:location].split(',') unless auth[:info][:location].nil?

    city ||=""
    country ||=""

    city.strip!
    country.strip!

    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        auth.info.email ||= "#{auth.uid}@facebook.com"
        user = User.create( name: auth.extra.raw_info.name,
                            first_name: auth.info.first_name,
                            last_name: auth.info.last_name,
                            provider: auth.provider,
                            uid: auth.uid,
                            email: auth.info.email,
                            password: Devise.friendly_token[0,20],
                            avatar_url: auth.info.image,
                            profile_url: auth.info.urls[:Facebook],
                            city: city,
                            country: country
                          )
      end
    end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user

  validates :youtube_url, presence: true
  validates :user_id, presence: true

  before_create :preprocess_data

  URL_Formats = {
        regular: /^(https?:\/\/)?(www\.)?youtube.com\/watch\?(.*\&)?v=([^&]+)/,
        shortened: /^(https?:\/\/)?(www\.)?youtu.be\/([^&]+)/,
        invalid_chars: /[^a-zA-Z0-9\:\/\?\=\&\$\-\_\.\+\!\*\'\(\)\,]/
    }

  private

  def has_invalid_chars?(youtube_url)
    !URL_Formats[:invalid_chars].match(youtube_url).nil?
  end

  def preprocess_data

    if self.hash_id.nil?
      curr_time = Time.now
      self.hash_id = Digest::SHA1.hexdigest(curr_time.to_s + curr_time.usec.to_s)[8..15]
    end

    if self.youtube_id.nil?
      self.youtube_id = extract_video_id(self.youtube_url)
    end

    if self.youtube_embed.nil?
      self.youtube_embed = youtube_embed_url(self.youtube_url)
    end
  end

  def extract_video_id(youtube_url)
    return nil if has_invalid_chars?(youtube_url)

    result = if match = URL_Formats[:regular].match(youtube_url)
      match[4]
    elsif match = URL_Formats[:shortened].match(youtube_url)
      match[3]
    else
      nil
    end

    result
  end

  def youtube_embed_url(youtube_url, width = 420, height = 315)
    return nil if has_invalid_chars?(youtube_url)

    vid_id = extract_video_id(youtube_url)
    %(<iframe width="#{width}" height="#{height}" src="http://www.youtube.com/embed/#{vid_id}?autoplay=1" frameborder="0" allowfullscreen></iframe>)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

  private

  def set_locale
    I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @videos = Video.order("id DESC").limit(10)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    Geocoder.configure(:language => I18n.locale)
    res = Geocoder.search("#{params[:latitude]},#{params[:longitude]}")

    res_json = res.first.data.as_json

    city = res_json["address_components"][3]["long_name"]
    country = res_json["address_components"].last["long_name"]

    render json: {city: city, country: country}
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    render "about_#{I18n.locale}"
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!, except: [:show]

  def new
    @resource = Video.new
  end

  def create
    @resource = Video.new(video_params)

    if @resource.save
      redirect_to action: "show", id: @resource.hash_id
    else
      render :new
    end
 end

  def show
    @video = Video.find_by_hash_id(params[:id])
  end

  private

  def video_params
    params[:video].merge!({user_id: current_user.id})
    params.require(:video).permit(:youtube_url, :user_id, :latitude, :longitude, :city, :country)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def video_city(video)
    return (video.city.blank? ? video.user.city : video.city)
  end

  def video_country(video)
    return (video.country.blank? ? video.user.country : country.city)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.slim
.video-list
  - @videos.each do |video|
    .video-item
      a href="#{video_path(video.hash_id)}" class="video-link"
        img.video-thumb src="http://img.youtube.com/vi/#{video.youtube_id}/mqdefault.jpg"
      div.info-box
        a href="#{video.user.profile_url}" target="_blank" class="info-box__link"
          img.info-box__profile-thumb src="#{video.user.avatar_url}"
          div.info-box__profile-name= video.user.name
          div.info-box__location= "#{video_city(video)}, #{video_country(video)}"

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div[class="alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}" data-alert]
      = content_tag :div, msg
      a.close[href="#"]
        | ×

app/views/layouts/_navigation.html.slim
/ navigation styled for Zurb Foundation 5
nav.top-bar[data-topbar]
  ul.title-area
    li.name
      = link_to 'Banderovtsev.net', root_path
  .top-bar-section
    ul.right
      == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li
  a href="#{pages_about_path}"= t("About")
li.active
  a href="#{new_video_path}"
    i.fa.fa-plus.fa-fw
    = t("Add Video")
/- if user_signed_in?
/  li= link_to 'Logout', destroy_user_session_path, :method=>'delete'
/- else
/  li= link_to 'Login', new_user_session_path
/
/- if user_signed_in?
/  li= link_to 'Edit account', edit_user_registration_path
/- else
/  li= link_to 'Sign up', new_user_registration_path
/
/li
/  .fb-login-button data-auto-logout-link="true" data-max-rows="1" data-show-faces="false" data-size="small" data-scope="basic_info,user_location"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Bandera'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Bandera'}"
    == stylesheet_link_tag "application", :media => "all"
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag "vendor/modernizr"
    == javascript_include_tag "application"
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield
    footer class="page-footer"
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-49232569-1', 'banderovtsev.net');
      ga('send', 'pageview');

app/views/pages/about_en.html.slim
.page-content
    h1 О проекте

    p
        'Прим.: значение слова «бандеровцы» (по Новому толковому словарю издания 2014 г.) – люди, преданные своему народу и любящие свою страну.

    p
        strong Кто мы: 
        'патриоты и не очень, сознательные граждане и те, кто к этому стремятся, люди, которые любят свою страну или учатся это делать, - обычные мирные граждане отовсюду.

    p 
        strong Кто не мы: 
        'экстремисты, террористы, фашисты

    p
        strong Чего мы хотим: 
        'мы хотим показать, что в нашей стране не разгуливают люди со свастикой, и никто не заклеивает рот скотчем тем, кто говорит по-русски. В нашей стране нет коричневой чумы. Информационная война, которую разжигают между нами в нашей стране, виртуальна. Ярлыки, что  навешивают на нас, недопустимы. Люди, которые вышли на улицы, вышли против коррупции правящей власти. Это простые люди,  они говорят на разных языках, но цель у них одна -  они хотят жить лучше.

    p
        strong Что сделать: 
        'снять коротенький видеоролик с утверждением «Я – бандеровец» на улицах своего города, на площади, в парке, кафе и так далее.  Вы вольны фантазировать сколько угодно.

    p
        strong Цели: 
        ul
            li разрядить обстановку
            li показать мифических бандеровцев
            li объединить нас всех в борьбе с кремлевской пропагандой
            li сплотить
            li посмеяться

app/views/pages/about_ru.html.slim
p Прим.: значение слова «бандеровцы» (по Новому толковому словарю издания 2014 г.) – люди, преданные своему народу и любящие свою страну.

p Кто мы:  патриоты и не очень, сознательные граждане и те, кто к этому стремятся, люди, которые любят свою страну или учатся это делать, - обычные мирные граждане отовсюду.

p Кто не мы: экстремисты, террористы, фашисты

p Чего мы хотим: мы хотим показать, что в нашей стране не разгуливают люди со свастикой, и никто не заклеивает рот скотчем тем, кто говорит по-русски. В нашей стране нет коричневой чумы. Информационная война, которую разжигают между нами в нашей стране, виртуальна. Ярлыки, что  навешивают на нас, недопустимы. Люди, которые вышли на улицы, вышли против коррупции правящей власти. Это простые люди,  они говорят на разных языках, но цель у них одна -  они хотят жить лучше.

p Что сделать: снять коротенький видеоролик с утверждением «Я – бандеровец» на улицах своего города, на площади, в парке, кафе и так далее.  Вы вольны фантазировать сколько угодно.

p Цели:
         разрядить обстановку
         показать мифических бандеровцев
         объединить нас всех в борьбе с кремлевской пропагандой
         сплотить
         посмеяться

app/views/pages/about_uk.html.slim
p Прим.: значение слова «бандеровцы» (по Новому толковому словарю издания 2014 г.) – люди, преданные своему народу и любящие свою страну.

p Кто мы:  патриоты и не очень, сознательные граждане и те, кто к этому стремятся, люди, которые любят свою страну или учатся это делать, - обычные мирные граждане отовсюду.

p Кто не мы: экстремисты, террористы, фашисты

p Чего мы хотим: мы хотим показать, что в нашей стране не разгуливают люди со свастикой, и никто не заклеивает рот скотчем тем, кто говорит по-русски. В нашей стране нет коричневой чумы. Информационная война, которую разжигают между нами в нашей стране, виртуальна. Ярлыки, что  навешивают на нас, недопустимы. Люди, которые вышли на улицы, вышли против коррупции правящей власти. Это простые люди,  они говорят на разных языках, но цель у них одна -  они хотят жить лучше.

p Что сделать: снять коротенький видеоролик с утверждением «Я – бандеровец» на улицах своего города, на площади, в парке, кафе и так далее.  Вы вольны фантазировать сколько угодно.

p Цели:
         разрядить обстановку
         показать мифических бандеровцев
         объединить нас всех в борьбе с кремлевской пропагандой
         сплотить
         посмеяться

app/views/videos/new.html.slim
.authform
  h3= t("Add Video")
  = form_for(@resource) do |f|
    = f.hidden_field :latitude, id: "video_latitude"
    = f.hidden_field :longitude, id: "video_longitude"
    = f.hidden_field :city, id: "video_city"
    = f.hidden_field :country, id: "video_country"
    div.form-group
      = f.label t("Youtube Video Url")
      - if !@resource.errors.blank? && !@resource.errors.messages[:youtube_url].blank?
        - @resource.errors.messages[:youtube_url].each do |error|
          small.error.medium.input-text.error= error
      = f.text_field :youtube_url, :autofocus => true, class: 'form-control'
    div.form-group
      label.location
        = t("Detecting your country and city")
        i.loading
        span= " "
        a.cancel-detect href="#" = t("cancel")
    div.form-group
      = f.submit 'Save', :class => 'button right'
javascript:

  function success(position) {

    $("label.location .cancel-detect").on("click", function() {
      $("label.location").remove();
    });

    $.ajax({
      url: "/location/get",
      data: {latitude: position.coords.latitude, longitude:position.coords.longitude},
      success: function(data, status) {
        var location_str = "";
        var remove_link = " <a href=\"#\" class=\"remove-detect\">" + "#{{t("remove")}}" + "</a>";

        //if got location - fill coordinates and city-country fields
        if (position.coords.latitude && position.coords.longitude) {
          $("#video_latitude").val(position.coords.latitude);
          $("#video_longitude").val(position.coords.longitude);
        }

        //if got city
        if (data['city'] !== "") {
          location_str += data['city'];
          $("#video_city").val(data['city']);
        }

        //if got country
        if (data['country'] !== "") {
          location_str += ", " + data['country'];
          $("#video_country").val(data['country']);
        }

        //if have location  then add link to remove it
        if (location_str !== "") {
          location_str += remove_link;
        }

        $("label.location").html(location_str)

        //bind "remove location" link
        $("label.location .remove-detect").on("click", function() {
          //remove text
          $("label.location").remove();

          //clean fields with location
          $("#video_latitude").val('');
          $("#video_longitude").val('');
          $("#video_city").val('');
          $("#video_country").val('');

        });
      },
      dataType: 'json'
    });
  }

  $(function() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(success);
    } else {
      error('not supported');
    }

  });

app/views/videos/show.html.slim
.page-content
    .flex-video= raw(@video.youtube_embed)